baseurl = "https://captain-exchange-57048.netlify.com/"   
title = "AP Statistics Poster Competition"
theme = "source-flask-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-106170280-1"

# Define the number of posts per page
paginate = 10


[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "With my experience in sales and magic, I help close the gap between the SGA and student orgs on campus."

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "sourceflaskio@gmail.com"

    copyright = """<p>made by SourceFlask, the consulting arm of <a href="https://www.facebook.com/UXSocChapmanU">User Experience Society ChapmanU</a></p>"""

    facebook= "https://www.facebook.com/APStatisticsPosterComp/"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    signup_link = "https://docs.google.com/forms/d/e/1FAIpQLSczuJC1zqXl6JmZyHndHfERookGTc_39AXzmV6zP30uh8g9QQ/viewform?usp=sf_link/"


[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.top_title_card]
    enable = true
    main_title = "<span>Join</span> the"
    second_title = "AP STATISTICS</br>POSTER COMPETITION"
    sub_title = "hosted at Chapman University on April 7, 2018"
    img = "img/top.jpg"

[params.morea_about]
    enable = true
    title = "More About The Event"
    text = """The Southern Californian Chapters of the American Statistical Association organized
          the AP Statistics Poster Competition as <strong>an avenue for aspiring statisticians</strong>
          from high school to shine with data-driven discovery through statistics.

          <br><br>

          <strong>60 teams will be chosen</strong> from those who apply and will be asked to
          <strong>present an informational poster</strong> about their study.
          Teams who place <strong>win up to $100.</strong></p>"""
    img = "img/about.jpg"

[params.call_to_action]
    enable = true
    main_tag = "Registration is ongoing!"
    sub_title = """Have any questions?<br>Get in touch with Dr. Criselda Toto:"""
    phone_number = "(714) 997-6782"
    email = "toto@chapman.edu"

[params.footer]
    main_title = "<span>Join</span> the"
    second_title = "AP STATISTICS<br>POSTER COMPETITION"
